実践編/chapter07/4_追加のページを作成する/learning_log/learning_logs/urls.py
"""learning_logsのURLパターンの定義"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # ホームページ
    path('', views.index, name='index'),
    # すべてのトピックを表示するページ
    path('topics/', views.topics, name='topics'),
    # 個別トピックの詳細ページ
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

実践編/chapter07/4_追加のページを作成する/learning_log/learning_logs/views.py
from django.shortcuts import render

from .models import Topic

def index(request):
    """学習ノートのホームページ"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """すべてのトピックを表示する"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """1つのトピックとそれについてのすべての記事を表示"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

実践編/chapter07/4_追加のページを作成する/learning_log/learning_logs/templates/learning_logs/base.html
<p>
  <a href="{% url 'learning_logs:index' %}">学習ノート</a> -
  <a href="{% url 'learning_logs:topics' %}">トピック一覧</a>
</p>

{% block content %}{% endblock content %}

実践編/chapter07/4_追加のページを作成する/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>学習ノートを使えば、好みのトピックについて学習していることを記録して、
      いつも最新の状態を把握できます。</p>
{% endblock content %}

実践編/chapter07/4_追加のページを作成する/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>トピック: {{ topic }}</p>

  <p>記事:</p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'Y年m月d日 H:i' }}</p>
      <p>{{ entry.text|linebreaks }}</p>
    </li>
  {% empty %}
    <li>このトピックにはまだ記事がありません。</li>
  {% endfor %}
  </ul>

{% endblock content %}

実践編/chapter07/4_追加のページを作成する/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>トピック一覧</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>トピックはまだ作成されていません。</li>
    {% endfor %}
  </ul>

{% endblock content %}